### ISSUE TITLE
Attribute error on dynamixel get_baud_rate

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_body#107]
```
hello-binit@stretch-re1-1002:~/repos2/stretch_body/body$ python3 -m unittest test.test_dynamixel_XL430
Testing changing baud rate from 57600 to 115200 and back
[Dynamixel ID:013] ping Succeeded. Dynamixel model number : 1060
ETesting Concurrent Access
[Dynamixel ID:012] ping Succeeded. Dynamixel model number : 1060
[Dynamixel ID:012] ping Succeeded. Dynamixel model number : 1060
[Dynamixel ID:012] ping Succeeded. Dynamixel model number : 1060
[Dynamixel ID:012] ping Succeeded. Dynamixel model number : 1060
[Dynamixel ID:012] ping Succeeded. Dynamixel model number : 1060
.Testing Handle Comm Result
.
======================================================================
ERROR: test_change_baud_rate (test.test_dynamixel_XL430.TestDynamixelXL430)
Verify can change baud rate.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hello-binit/repos2/stretch_body/body/test/test_dynamixel_XL430.py", line 73, in test_change_baud_rate
    curr_baud = servo1.get_baud_rate()
  File "/home/hello-binit/repos2/stretch_body/body/stretch_body/dynamixel_XL430.py", line 301, in get_baud_rate
    return BAUD_MAP.keys()[BAUD_MAP.values().index(p)]
AttributeError: 'dict_values' object has no attribute 'index'

----------------------------------------------------------------------
Ran 3 tests in 0.294s

FAILED (errors=1)
hello-binit@stretch-re1-1002:~/repos2/stretch_body/body$
```

**Comment by aedsinger** [comment]
Fixed with PR https://github.com/hello-robot/stretch_body/pull/116
