### ISSUE TITLE
Using the --range flag on stretch_rp_lidar_jog tool errors

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_body#154]
Running `stretch_rp_lidar_jog.py --range` yeilds the following error:
```
$ stretch_rp_lidar_jog.py --range
For use with S T R E T C H (R) RESEARCH EDITION from Hello Robot Inc.
---------------------------------------------------------------------

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/hello-robot/.local/bin/stretch_rp_lidar_jog.py", line 42, in <module>
    for i, scan in enumerate(lidar.iter_scans()):
  File "/home/hello-robot/.local/lib/python3.8/site-packages/rplidar.py", line 446, in iter_scans
    for new_scan, quality, angle, distance in iterator:
  File "/home/hello-robot/.local/lib/python3.8/site-packages/rplidar.py", line 383, in iter_measures
    self.start(scan_type)
  File "/home/hello-robot/.local/lib/python3.8/site-packages/rplidar.py", line 319, in start
    status, error_code = self.get_health()
  File "/home/hello-robot/.local/lib/python3.8/site-packages/rplidar.py", line 279, in get_health
    dsize, is_single, dtype = self._read_descriptor()
  File "/home/hello-robot/.local/lib/python3.8/site-packages/rplidar.py", line 214, in _read_descriptor
    raise RPLidarException('Descriptor length mismatch')
rplidar.RPLidarException: Descriptor length mismatch
```

On Ubuntu 20.04, Python 3.8.10, stretch_body==0.4.2.dev0, stretch_body_tools==0.4.0.dev0.

**Comment by hello-binit** [comment]
Solved by upgrading to the latest 0.4 stretch_body/tools releases.
