### ISSUE TITLE
'trajectory_vel_ctrl' KeyError from runstop

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_body#161]
While Stretch Body is running, pressing the runstop button causes a KeyError to be emitted. Tested on a RE1 configured with a Dex Wrist, 20.04, Py3.8, Stretch Body==0.4.8.

```python
In [1]: import stretch_body.robot                                                                                                       

In [2]: r = stretch_body.robot.Robot()                                                                                                  

In [3]: r.startup()                                                                                                                     
[WARNING] [head_tilt]: Dynamixel head_tilt: Servo is in single-turn mode yet has invalid homing offset of -1682. 
 This may cause unexpected results if not set to zero (using REx_dynamixel_jog.py)
 Please contact Hello Robot support for more information
Out[3]: True

In [4]: r.stow()                                                                                                                        
--------- Stowing Arm ----
--------- Stowing ToolStretchDexWrist ----
--------- Stowing Lift ----

In [5]: [INFO] [robot_monitor]: Runstop activated                                                                                       
[INFO] [robot_monitor]: Base bump event
Exception in thread Thread-428:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/hello-binit/.local/lib/python3.8/site-packages/stretch_body/robot.py", line 86, in run
    self.robot._step_sentry()
  File "/home/hello-binit/.local/lib/python3.8/site-packages/stretch_body/robot.py", line 379, in _step_sentry
    self.end_of_arm.step_sentry(self)
  File "/home/hello-binit/.local/lib/python3.8/site-packages/stretch_body/dynamixel_X_chain.py", line 248, in step_sentry
    self.motors[k].step_sentry(robot)
  File "/home/hello-binit/.local/lib/python3.8/site-packages/stretch_tool_share/stretch_dex_wrist/wrist_pitch.py", line 34, in step_sentry
    DynamixelHelloXL430.step_sentry(self,robot)
  File "/home/hello-binit/.local/lib/python3.8/site-packages/stretch_body/dynamixel_hello_XL430.py", line 379, in step_sentry
    self.stop_trajectory()
  File "/home/hello-binit/.local/lib/python3.8/site-packages/stretch_body/dynamixel_hello_XL430.py", line 639, in stop_trajectory
    if self.params['motion']['trajectory_vel_ctrl']:
KeyError: 'trajectory_vel_ctrl'
```

The runstop button was pressed at `In [5]`.

**Comment by hello-binit** [comment]
This exception means the wrist_pitch joint from Stretch Tool Share doesn't have the "trajectory_vel_ctrl" key. This could be because Stretch Tool Share needs to be updated: `pip3 install -U hello-robot-stretch-tool-share`.

**Comment by hello-binit** [comment]
Fixed in https://github.com/hello-robot/stretch_tool_share/commit/a26fbf4fa0394efa61f7d932a382f4249c4395fe
