### ISSUE TITLE
Stalls on exit

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_body#210]
I'm running Stretch Body locally (commit a30c350497a2abc8616958f1bc77af6234e94ddb - latest on main currently), and I'm using the Robot class from iPython and a python script. The issue I'm seeing happens when the script is exiting: the Robot class stalls with the following exception and the program doesn't end until I input Ctrl-C.

```python
$ ipython3
In [1]: import stretch_body.robot

In [2]: r = stretch_body.robot.Robot()

In [3]: r.startup()
Out[3]: True

In [4]:                                                                                                                                 
Do you really want to exit ([y]/n)? y
Exception in thread NonDXLStatusThread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/robot.py", line 111, in run
    self.step()
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/robot.py", line 97, in step
    asyncio.get_event_loop().run_until_complete(asyncio.gather(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/wacc.py", line 122, in pull_status_async
    await self.transport.do_pull_rpc_async(payload, self.rpc_status_reply, exiting=exiting)
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/transport.py", line 885, in do_pull_rpc_async
    await asyncio.get_event_loop().run_in_executor(None, self.lock.acquire)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown

# Ctrl-C HERE!
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt: 

```

The correct behavior is for the program to exit without any output or error, as Stretch Body <=v0.4 did before. Disabling asyncio (using `use_asyncio: 0` in user params) silences the exception, but doesn't solve the stalling behavior. Explicitly calling `robot.stop()` at the end of the script results in correct behavior, but it should not be necessary to call `robot.stop()`.

**Comment by hello-fazil** [comment]
This bug has been fixed with this commits from this PR https://github.com/hello-robot/stretch_body/pull/236
