### ISSUE TITLE
Error from GripperConversion with RE2 Model

### ISSUE THREAD

**Issue by hello-fazil** [hello-robot/stretch_body#266]
```
$ stretch_robot_home.py 
For use with S T R E T C H (R) from Hello Robot Inc.
---------------------------------------------------------------------

--------- Homing Head ----
Caught Exception in Thread: SystemMonitorThread
--------- Homing Lift ----
Homing Lift...
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/hello-robot/.local/lib/python3.10/site-packages/stretch_body/robot.py", line 170, in run
    self.step()
  File "/home/hello-robot/.local/lib/python3.10/site-packages/stretch_body/robot.py", line 160, in step
    self.robot.collision.step()
  File "/home/hello-robot/.local/lib/python3.10/site-packages/stretch_body/robot_collision.py", line 206, in step
    cfg = self.get_joint_configuration(braked=True)#_braked()
  File "/home/hello-robot/.local/lib/python3.10/site-packages/stretch_body/robot_collision.py", line 319, in get_joint_configuration
    configuration.update(self.robot.end_of_arm.get_joint_configuration(braked))
  File "/home/hello-robot/.local/lib/python3.10/site-packages/stretch_body/end_of_arm_tools.py", line 31, in get_joint_configuration
    _, gripper_finger_rad, _, _ = g.gripper_conversion.status_to_all(g.status)
AttributeError: 'GripperConversion' object has no attribute 'status_to_all'

```

**Comment by aedsinger** [comment]
Fixed in PR https://github.com/hello-robot/stretch_body/pull/267
