### ISSUE TITLE
Head() group startup errors out when head_tilt/head_pan params are removed from config params yaml in RE2

### ISSUE THREAD

**Issue by hello-fazil** [hello-robot/stretch_body#286]
The Head() class which is a Subclass DynamixelXChain() errors out looking for non-existent dxl_id variable from head_pan and head_tilt device. This issue appears to occur only when no head_pan and head_tilt params are defined in the stretch_confguration_params.yaml or stretch_user_params.yaml. Reproduced in RE2
```
$ stretch_head_jog.py 
For use with S T R E T C H (R) from Hello Robot Inc.
---------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/hello-robot/.local/bin/stretch_head_jog.py", line 15, in <module>
    if not h.startup(threaded=False):
  File "/home/hello-robot/.local/lib/python3.10/site-packages/stretch_body/head.py", line 24, in startup
    return DynamixelXChain.startup(self, threaded=threaded)
  File "/home/hello-robot/.local/lib/python3.10/site-packages/stretch_body/dynamixel_X_chain.py", line 83, in startup
    if not self.readers[k].addParam(self.motors[mk].motor.dxl_id):
AttributeError: 'NoneType' object has no attribute 'dxl_id'
```

**Comment by hello-fazil** [comment]
This PR #298 fixes this issue.
